import {i18n} from '@/infra/translate/i18n';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Rafael Castro',
  description: 'Generated by create next app',
};

interface Props {
  children: any;
  params: {lang: string};
}

export async function generateStaticParams() {
  const languages = i18n.locales.map(lang => ({lang}));
  return languages;
}

export default function RootLayout({children, params: {lang}}: Props) {
  return (
    <html lang={lang}>
      <meta name="theme-color" content="#08161c" />
      <head />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
